-- -- Smart directional movement in Neovim
-- local directions = {
--   h = "left",
--   j = "down",
--   k = "up",
--   l = "right"
-- }
--
-- local function smart_window_move(key)
--   local dir = directions[key]
--   local cur_win = vim.api.nvim_get_current_win()
--   vim.cmd("wincmd " .. key)
--   local new_win = vim.api.nvim_get_current_win()
--
--   if cur_win == new_win then
--     -- No window in that direction — optionally: let terminal handle it
--     -- Or: simulate keypress to send to tmux/terminal
--     -- Here we do nothing so key falls through
--   end
-- end
--
-- -- Bind keys to smart movement
-- for key, _ in pairs(directions) do
--   vim.keymap.set("n", "<C-" .. key .. ">", function()
--     smart_window_move(key)
--   end, { silent = true })
-- end
--
return {}
